"""Harness generation — KavachX writes the code, the spec supplies only values.

This is where a :class:`~app.testing.specs.TestSpec` becomes something executable, and it is the
single most security-sensitive module in the testing subsystem. The rule it enforces:

    **No string from a model ever becomes code.**

Every harness is produced from a template authored here. The spec contributes *values* — a target
symbol, a payload string, a timeout, a field name — and each value is inserted through
``json.dumps`` or as an argv element, never by string concatenation into a code position. A payload
containing ``"); os.system("rm -rf /`` therefore lands in the generated file as a quoted Python
string literal and stays data.

The generated harness is written into ``_kavachx/tests/`` inside the workspace, which is already
excluded from the pinned-source hash and preserved across gauntlet resets. It is collected as a
run artifact, so the demo's "the generated test is saved" requirement is satisfied by the same
mechanism that makes the test auditable.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.core.hashing import sha256_text
from app.core.logging import get_logger
from app.discovery.base import CANARY_CONTENT, CANARY_FILENAME, POV_MARKER
from app.testing.specs import TestPlan, TestPlanStatus, TestSpec

logger = get_logger(__name__)

#: Where generated harnesses live inside the workspace.
HARNESS_DIR = "_kavachx/tests"

#: A generated file always carries this banner. It makes a harness identifiable in a diff, in an
#: artifact listing, and in a target repository if one is ever accidentally copied there.
_BANNER = """# GENERATED BY KAVACHX — DO NOT EDIT
#
# This harness was generated from a validated TestSpec by app/testing/harness.py.
# Every value below was inserted as a data literal; no model-supplied text is executable here.
#
#   plan_id : {plan_id}
#   target  : {target}
#   strategy: {strategy}
#   oracle  : {oracle}
#   property: {prop}
"""


@dataclass
class GeneratedHarness:
    ok: bool = False
    #: Workspace-relative path.
    path: str = ""
    content: str = ""
    sha256: str = ""
    #: The argv the sandbox runs. Built here, never model-supplied.
    command: list[str] = field(default_factory=list)
    #: Marker values injected for marker/canary oracles.
    markers: dict[str, str] = field(default_factory=dict)
    #: Files the harness writes that should be collected back out of the sandbox.
    artifacts: list[str] = field(default_factory=list)
    error: str = ""
    notes: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "path": self.path,
            "sha256": self.sha256,
            "command": self.command,
            # Markers are KavachX-generated constants, not secrets: they must appear in the
            # record because reproducing a finding requires knowing which marker was planted.
            "markers": dict(self.markers),
            "artifacts": self.artifacts,
            "error": self.error,
            "notes": self.notes,
        }


def _banner(plan: TestPlan) -> str:
    return _BANNER.format(
        plan_id=plan.plan_id[:16],
        target=plan.spec.target,
        strategy=plan.spec.strategy,
        oracle=plan.spec.oracle.kind,
        prop=plan.spec.expected_security_property[:120].replace("\n", " "),
    )


#: Types a spec value may have. Anything else is a bug in the spec layer, not something to render.
_PLAIN_TYPES = (str, int, float, bool, type(None), list, tuple, dict)


def _assert_plain(value: Any) -> None:
    """Reject anything that is not a plain JSON-shaped value.

    This is the guard that makes literal rendering safe: ``repr`` of an unexpected object emits
    ``<object at 0x...>``, which is a syntax error in the generated file. Failing loudly here
    surfaces it as a harness-generation error instead.
    """
    if not isinstance(value, _PLAIN_TYPES):
        raise TypeError(
            f"cannot render {type(value).__name__} as a literal; spec values must be plain "
            "JSON-shaped data"
        )
    if isinstance(value, (list, tuple)):
        for item in value:
            _assert_plain(item)
    elif isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise TypeError("literal dict keys must be strings")
            _assert_plain(item)


def _py_lit(value: Any) -> str:
    """Render a **Python** literal for a value from the spec.

    ``repr``, not ``json.dumps``. JSON is *not* a subset of Python literal syntax: it renders
    booleans as ``true``/``false`` and null as ``null``, none of which are Python. Using
    ``json.dumps`` here produced generated harnesses containing ``if true:`` that died with
    ``NameError: name 'true' is not defined`` at line 1 of execution — a whole strategy silently
    failing to run, reported as "the oracle did not fire".

    ``repr`` of any value that passes :func:`_assert_plain` is a valid Python literal, and nested
    containers are handled correctly by recursion inside ``repr`` itself.
    """
    _assert_plain(value)
    return repr(value)


def _js_lit(value: Any) -> str:
    """Render a **JavaScript/JSON** literal. Here ``json.dumps`` is exactly right."""
    _assert_plain(value)
    return json.dumps(value, ensure_ascii=True)


# ---------------------------------------------------------------------------
def generate(
    plan: TestPlan,
    *,
    workspace: Path,
    descriptor: Any = None,
) -> GeneratedHarness:
    """Generate the harness for ``plan``. Dispatches on (language, strategy)."""
    spec = plan.spec
    language = plan.language or "python"
    key = (language, spec.strategy)

    generator = {
        ("python", "unit"): _python_unit,
        ("python", "regression"): _python_unit,
        ("python", "mutation"): _python_mutation,
        ("python", "property"): _python_property,
        ("python", "fuzz"): _python_fuzz,
        ("python", "differential"): _python_differential,
        ("c", "fuzz"): _c_libfuzzer,
        ("c", "unit"): _c_libfuzzer,
        ("c", "regression"): _c_libfuzzer,
        ("javascript", "property"): _js_property,
        ("javascript", "unit"): _js_unit,
        ("javascript", "regression"): _js_unit,
        ("go", "fuzz"): _go_fuzz,
    }.get(key)

    if generator is None:
        return GeneratedHarness(
            error=(
                f"KavachX has no harness generator for ({language}, {spec.strategy}). The "
                f"{spec.strategy} strategy did NOT run for this target."
            )
        )

    try:
        harness = generator(plan, workspace, descriptor)
    except Exception as exc:  # pragma: no cover - generator bug, must not kill the run
        logger.exception("testing.harness_generation_failed", plan=plan.plan_id[:16])
        return GeneratedHarness(
            error=f"harness generation raised {type(exc).__name__}: {str(exc)[:300]}"
        )

    if harness.ok and harness.content:
        target = workspace / harness.path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(harness.content, encoding="utf-8", newline="\n")
        harness.sha256 = sha256_text(harness.content)
        logger.info(
            "testing.harness_generated",
            plan=plan.plan_id[:16],
            path=harness.path,
            strategy=spec.strategy,
            engine=plan.engine,
            bytes=len(harness.content),
        )
    return harness


def _stem(plan: TestPlan) -> str:
    """A filesystem-safe stem derived from the plan id, not from model-supplied text."""
    return f"kx_{plan.spec.strategy}_{plan.plan_id[:12]}"


def _request_payloads(spec: TestSpec) -> list[dict[str, Any]]:
    """Build the concrete request objects the harness will send.

    The template comes from the spec but is rebuilt here field by field, so a template key cannot
    smuggle in a nested structure the harness does not expect.
    """
    out: list[dict[str, Any]] = []
    template = {str(k): v for k, v in (spec.request_template or {}).items()}
    if not spec.payloads:
        return [template] if template else []
    for payload in spec.payloads:
        request = dict(template)
        if spec.payload_field:
            request[spec.payload_field] = payload
        out.append(request)
    return out


# ---------------------------------------------------------------------------
# Python
# ---------------------------------------------------------------------------
def _python_driver_preamble(
    plan: TestPlan, descriptor: Any, *, mode: str = "subprocess"
) -> str:
    """Shared harness preamble: locate the target and expose a ``drive()`` helper.

    The entry module/callable/file come from the *confirmed* descriptor — the one the probe
    verified against the filesystem — not from the spec, so a spec naming a non-existent
    entrypoint cannot produce a harness that imports something arbitrary.

    Two driving modes, and the distinction is load-bearing:

    ``subprocess``
        Spawns the target as its own process, exactly as the existing validator does, and reads
        the real process stdout. This is the mode the *prover* strategies use, because a vulnerable
        target can write to file descriptor 1 from a shell it spawned, and
        ``contextlib.redirect_stdout`` only rebinds Python's ``sys.stdout`` — it would not see
        that output at all. Missing a signal is the one failure mode a prover must not have.

    ``in_process``
        Imports the entrypoint and calls it with an argv list (which is what the confirmed
        entrypoint takes — ``main(argv)`` — not a request dict), capturing Python-level streams.
        Used for the maintainer-facing pytest and property harnesses, where a normal in-process
        test is the idiomatic thing to hand someone. Its coverage of subprocess output is
        best-effort and it is never the sole basis for a validated finding.
    """
    source_root = getattr(descriptor, "source_root", ".") or "."
    entry_module = getattr(descriptor, "entry_module", "") or ""
    entry_callable = getattr(descriptor, "entry_callable", "") or ""
    entry_file = getattr(descriptor, "entry_file", "") or ""

    common = f'''import json
import os
import sys
import traceback

# Confirmed by the probe against the filesystem, not proposed by a model.
_SOURCE_ROOT = {_py_lit(source_root)}
_ENTRY_MODULE = {_py_lit(entry_module)}
_ENTRY_CALLABLE = {_py_lit(entry_callable)}
_ENTRY_FILE = {_py_lit(entry_file)}

sys.path.insert(0, os.path.abspath(_SOURCE_ROOT))

KX_MARKER = {_py_lit(POV_MARKER)}
KX_CANARY_CONTENT = {_py_lit(CANARY_CONTENT)}
KX_CANARY_FILENAME = {_py_lit(CANARY_FILENAME)}


def _argv_for(request):
    """The argv the target's entrypoint expects: a single --request JSON document."""
    return ["--request", json.dumps(request, sort_keys=True)]
'''

    if mode == "in_process":
        return common + '''

def _load_entry():
    """Import the confirmed entrypoint callable."""
    if not _ENTRY_MODULE:
        raise RuntimeError("no entry module was confirmed for this target")
    module = __import__(_ENTRY_MODULE, fromlist=["*"])
    fn = getattr(module, _ENTRY_CALLABLE, None)
    if fn is None:
        raise RuntimeError("entry callable %r not found in %r" % (_ENTRY_CALLABLE, _ENTRY_MODULE))
    return fn


def drive(request):
    """Call the entrypoint in-process with argv. Returns (ok, stdout_text, stderr_text)."""
    import contextlib
    import io

    fn = _load_entry()
    out, err = io.StringIO(), io.StringIO()
    code = 0
    try:
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = fn(_argv_for(request))
    except SystemExit as exc:  # argparse and sys.exit both raise this
        code = exc.code if isinstance(exc.code, int) else 1
    except Exception:
        return False, out.getvalue(), err.getvalue() + traceback.format_exc()
    return (code in (0, None)), out.getvalue(), err.getvalue()
'''

    return common + '''

def drive(request):
    """Run the target as its own process. Returns (ok, stdout_text, stderr_text).

    A separate process is what makes stdout capture complete: output written to fd 1 by a shell
    the target spawned is visible here and invisible to an in-process capture.
    """
    import subprocess

    argv = [sys.executable, _ENTRY_FILE] + _argv_for(request)
    try:
        completed = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=os.getcwd(),
        )
    except subprocess.TimeoutExpired:
        return False, "", "KAVACHX_TIMEOUT: the target did not finish within 30s"
    except Exception:
        return False, "", traceback.format_exc()
    return completed.returncode == 0, completed.stdout, completed.stderr
'''


def _python_unit(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """A unit/regression harness that is both a pytest module and a self-running script.

    Dual-mode on purpose. The file defines ordinary ``test_*`` functions, so a maintainer who
    receives it alongside the patch can run it with their own pytest. But KavachX executes it as
    ``python <file>`` through the ``__main__`` block below, because **pytest is not guaranteed to
    exist in the sandbox interpreter**: measured on this host, ``python -m pytest`` inside the dev
    sandbox resolved to the uv base interpreter and failed with ``No module named pytest``, so the
    whole strategy silently produced "the oracle did not fire" against a target with a live,
    reproducible command injection.

    Depending on a third-party runner for KavachX's own verification was the mistake. The
    self-running path has no dependency beyond the standard library, so this strategy cannot be
    disabled by the sandbox image's package list.
    """
    spec = plan.spec
    requests = _request_payloads(spec)
    oracle_kind = spec.oracle.kind

    tests = []
    for index, request in enumerate(requests, start=1):
        tests.append(f'''

def test_security_property_{index:03d}():
    """{spec.expected_security_property[:200]}"""
    request = {_py_lit(request)}
    ok, rendered, error = drive(request)
    combined = rendered + error

    # Oracle: {oracle_kind}
    signal = {_oracle_expression(oracle_kind)}
    # A generated security test FAILS when the property is violated. The runner's exit code is
    # therefore the deterministic signal the validator reads.
    assert not signal, (
        "SECURITY PROPERTY VIOLATED: {spec.expected_security_property[:120]} | "
        + combined[:600]
    )
''')

    runner = '''

def _run_all():
    """Self-running mode: execute every test in this module without pytest.

    Prints the violation to stdout and exits non-zero, which is exactly the signal shape the
    marker/canary oracles read from the process output.
    """
    failures = []
    for name, fn in sorted(globals().items()):
        if not name.startswith("test_") or not callable(fn):
            continue
        try:
            fn()
        except AssertionError as exc:
            failures.append((name, str(exc)))
        except Exception:
            failures.append((name, traceback.format_exc()))
    for name, message in failures:
        print("FAILED %s: %s" % (name, message))
    print(json.dumps({"tests": sum(
        1 for n, f in globals().items() if n.startswith("test_") and callable(f)
    ), "failures": len(failures)}, sort_keys=True))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(_run_all())
'''

    content = (
        _banner(plan)
        # In-process: a file a maintainer keeps should read like a normal test.
        + _python_driver_preamble(plan, descriptor, mode="in_process")
        + "".join(tests)
        + runner
    )
    path = f"{HARNESS_DIR}/{_stem(plan)}.py"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        # Self-running, not `python -m pytest`. See the docstring.
        command=["python", path],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
        notes=[
            f"{len(requests)} case(s) generated from the spec's payloads.",
            "Dual-mode: KavachX runs it as a script; it is also a valid pytest module for the "
            "maintainer.",
        ],
    )


def _oracle_expression(kind: str) -> str:
    """The in-harness boolean for an oracle, as a code fragment from a fixed table.

    A fixed table, not a formatted string from the spec: this fragment is the one place in the
    generated file that is genuinely code rather than data, so its content can only ever be one of
    these literals.
    """
    return {
        "marker_in_stdout": "KX_MARKER in combined",
        "canary_content_in_stdout": "KX_CANARY_CONTENT in combined",
        "exception_raised": "not ok",
        "assertion_failure": '"AssertionError" in error',
        "exit_code_nonzero": "not ok",
        "crash_signal": "not ok",
        "timeout": "False  # a timeout is observed by the sandbox, not from inside the harness",
        "resource_exhaustion": '"MemoryError" in error or "RecursionError" in error',
        "no_crash": "not ok",
    }.get(kind, "not ok")


def _python_mutation(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """Deterministic mutation of the spec's payloads through KavachX-owned operators.

    The mutation operators live in the generated file as a fixed table. The spec chooses *which
    families* to apply; it never supplies an operator, because an operator is code.
    """
    spec = plan.spec
    families = list(spec.fuzz.mutations) if spec.fuzz else ["separator_injection"]
    template = {str(k): v for k, v in (spec.request_template or {}).items()}

    content = (
        _banner(plan)
        # The prover drives the target as a separate process so shell output cannot be missed.
        + _python_driver_preamble(plan, descriptor, mode="subprocess")
        + f'''
BASE_PAYLOADS = {_py_lit(spec.payloads)}
FAMILIES = {_py_lit(families)}
TEMPLATE = {_py_lit(template)}
FIELD = {_py_lit(spec.payload_field)}

# KavachX-owned mutation operators. The spec selects families; it cannot add an operator.
OPERATORS = {{
    "separator_injection": lambda v: [
        v + sep + "echo " + KX_MARKER
        for sep in ["&", ";", "|", "&&", "||", "`", "$(", "\\n", ">"]
    ],
    "traversal_sequences": lambda v: [
        p + KX_CANARY_FILENAME
        for p in ["../", "..\\\\", "a/../../", "./../", ".../.././", "..%2f"]
    ],
    "boundary_values": lambda v: ["", "0", "-1", "1", "2147483647", "-2147483648"],
    "negative_numbers": lambda v: ["-1", "-2", "-2147483648", "-0"],
    "large_values": lambda v: ["9" * 32, "9" * 256, str(2 ** 63)],
    "empty_and_null": lambda v: ["", " ", "\\t", "null", "None"],
    "type_confusion": lambda v: ["[]", "{{}}", "true", "0", '"' + str(v) + '"'],
    "encoding_variants": lambda v: [
        str(v).replace("/", "%2f"), str(v).upper(), str(v).lower(),
        "".join("%%%02x" % ord(c) for c in str(v)[:24]),
    ],
    "length_escalation": lambda v: [str(v) * n for n in (2, 8, 32, 128)],
    "unicode_edge_cases": lambda v: ["\\u0000", "\\uffff", "\\u202e", "e\\u0301", "\\U0001f4a9"],
    "format_specifiers": lambda v: ["%s%s%s", "%n", "{{0}}", "${{7*7}}", "{{{{7*7}}}}"],
    "structural_nesting": lambda v: ["[" * 32 + "]" * 32, "{{" * 32 + "}}" * 32],
}}


def variants():
    seen = set()
    for base in BASE_PAYLOADS or [""]:
        for family in FAMILIES:
            operator = OPERATORS.get(family)
            if operator is None:
                continue
            for candidate in operator(base):
                if candidate not in seen:
                    seen.add(candidate)
                    yield family, candidate


def main():
    findings = []
    attempted = 0
    for family, payload in variants():
        attempted += 1
        request = dict(TEMPLATE)
        if FIELD:
            request[FIELD] = payload
        ok, rendered, error = drive(request)
        combined = rendered + error
        signal = {_oracle_expression(spec.oracle.kind)}
        if signal:
            findings.append({{"family": family, "payload": payload[:400],
                              "evidence": combined[:400]}})
            if {_py_lit(bool(spec.fuzz.stop_on_first_signal) if spec.fuzz else True)}:
                break

    report = {{"attempted": attempted, "findings": findings}}
    os.makedirs(os.path.dirname({_py_lit(HARNESS_DIR + "/out/x")}), exist_ok=True)
    with open({_py_lit(f"{HARNESS_DIR}/out/{_stem(plan)}.json")}, "w", encoding="utf-8") as fh:
        json.dump(report, fh, sort_keys=True)
    print(json.dumps(report, sort_keys=True))
    # Non-zero exit when the property was violated: the sandbox reads this as the signal.
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
'''
    )
    path = f"{HARNESS_DIR}/{_stem(plan)}.py"
    report_path = f"{HARNESS_DIR}/out/{_stem(plan)}.json"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["python", path],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
        artifacts=[report_path],
        notes=[f"mutation families: {', '.join(families)}"],
    )


def _python_property(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """A Hypothesis property test.

    ``property_expression`` is compiled by the SAMHITA clause compiler — the same restricted-AST
    whitelist that rejects calls, attribute access and subscripts — *before* the harness is
    generated. So the expression that reaches the file has already been proven to be a pure
    boolean over named metrics, and cannot execute anything.
    """
    spec = plan.spec
    from app.samhita.compiler import try_compile

    compiled, error = try_compile(spec.property_expression)
    if compiled is None:
        return GeneratedHarness(
            error=(
                f"property_expression rejected by the clause compiler: {error}. The property "
                "strategy did NOT run for this spec."
            )
        )

    template = {str(k): v for k, v in (spec.request_template or {}).items()}
    content = (
        _banner(plan)
        + _python_driver_preamble(plan, descriptor, mode="in_process")
        + f'''
from hypothesis import given, settings, strategies as st, HealthCheck

TEMPLATE = {_py_lit(template)}
FIELD = {_py_lit(spec.payload_field or "value")}

# The invariant, already validated by the SAMHITA restricted-AST compiler as a pure boolean
# expression over the names below. It cannot call anything.
_PREDICATE_SOURCE = {_py_lit(compiled.predicate)}


def _evaluate(namespace):
    return bool(eval(compile(_PREDICATE_SOURCE, "<kx-property>", "eval"),
                     {{"__builtins__": {{}}}}, dict(namespace)))


@settings(max_examples={min(spec.fuzz.max_iterations if spec.fuzz else 200, 2000)},
          deadline=None,
          suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much])
@given(value=st.one_of(st.text(max_size=512), st.integers(), st.binary(max_size=256).map(
    lambda b: b.decode("utf-8", errors="replace"))))
def test_invariant(value):
    """{spec.expected_security_property[:200]}"""
    request = dict(TEMPLATE)
    request[FIELD] = value
    ok, rendered, error = drive(request)
    namespace = {{
        "ok": ok,
        "response_len": len(rendered),
        "error_len": len(error),
        "input_len": len(str(value)),
        "marker_present": int(KX_MARKER in (rendered + error)),
        "canary_present": int(KX_CANARY_CONTENT in (rendered + error)),
        "crashed": int(not ok),
    }}
    assert _evaluate(namespace), (
        "INVARIANT VIOLATED: " + _PREDICATE_SOURCE + " | input=" + repr(value)[:200]
    )
'''
    )
    path = f"{HARNESS_DIR}/{_stem(plan)}.py"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["python", "-m", "pytest", path, "-q", "-p", "no:cacheprovider"],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
        notes=[f"invariant: {compiled.predicate}", f"metrics: {sorted(compiled.metrics)}"],
    )


def _python_fuzz(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """Atheris when available, otherwise the builtin mutational engine.

    The choice is already made by :mod:`app.testing.engines`; this honours it. Falling through to
    the mutational harness rather than failing is what keeps a target with no Atheris from having
    zero fuzz coverage.
    """
    if plan.engine == "atheris":
        spec = plan.spec
        template = {str(k): v for k, v in (spec.request_template or {}).items()}
        content = (
            _banner(plan)
            # Atheris instruments the running interpreter, so it must drive in-process.
            + _python_driver_preamble(plan, descriptor, mode="in_process")
            + f'''
import atheris

TEMPLATE = {_py_lit(template)}
FIELD = {_py_lit(spec.payload_field or "value")}


def one_input(data):
    fdp = atheris.FuzzedDataProvider(data)
    value = fdp.ConsumeUnicodeNoSurrogates(4096)
    request = dict(TEMPLATE)
    request[FIELD] = value
    ok, rendered, error = drive(request)
    combined = rendered + error
    signal = {_oracle_expression(spec.oracle.kind)}
    if signal:
        # Raising is how libFuzzer records a crashing input and writes the reproducer.
        raise RuntimeError("KAVACHX_ORACLE_FIRED: " + combined[:400])


atheris.Setup(sys.argv, one_input)
atheris.Fuzz()
'''
        )
        path = f"{HARNESS_DIR}/{_stem(plan)}.py"
        iterations = spec.fuzz.max_iterations if spec.fuzz else 1000
        return GeneratedHarness(
            ok=True,
            path=path,
            content=content,
            command=[
                "python",
                path,
                f"-runs={iterations}",
                "-max_total_time=60",
                f"-artifact_prefix={HARNESS_DIR}/out/",
            ],
            markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
            artifacts=[],
            notes=["Atheris/libFuzzer coverage-guided fuzzing."],
        )
    return _python_mutation(plan, workspace, descriptor)


def _python_differential(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """Record a response hash per input so before/after builds can be compared byte-for-byte."""
    spec = plan.spec
    requests = _request_payloads(spec) or [{}]
    content = (
        _banner(plan)
        # Before/after comparison must see exactly what a real invocation produces.
        + _python_driver_preamble(plan, descriptor, mode="subprocess")
        + f'''
import hashlib

REQUESTS = {_py_lit(requests)}


def main():
    rows = []
    for index, request in enumerate(REQUESTS):
        ok, rendered, error = drive(request)
        rows.append({{
            "index": index,
            "ok": ok,
            # The hash, not the body: a differential comparison needs equality, and storing the
            # body would put target output into an artifact for no benefit.
            "response_sha256": hashlib.sha256(rendered.encode("utf-8")).hexdigest(),
            "error_class": error.strip().splitlines()[-1][:200] if error else "",
        }})
    out = {{"cases": rows}}
    os.makedirs({_py_lit(HARNESS_DIR + "/out")}, exist_ok=True)
    with open({_py_lit(f"{HARNESS_DIR}/out/{_stem(plan)}.json")}, "w", encoding="utf-8") as fh:
        json.dump(out, fh, sort_keys=True)
    print(json.dumps(out, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
    )
    path = f"{HARNESS_DIR}/{_stem(plan)}.py"
    report = f"{HARNESS_DIR}/out/{_stem(plan)}.json"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["python", path],
        artifacts=[report],
        notes=["Response hashes per input, for before/after comparison."],
    )


# ---------------------------------------------------------------------------
# C
# ---------------------------------------------------------------------------
def _c_libfuzzer(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    """A libFuzzer entrypoint plus a sanitizer-instrumented build command.

    The target function is called through a declared prototype rather than by including a header
    KavachX has not verified exists. If the symbol does not link, the build fails loudly at
    compile time — which is the honest outcome — instead of the harness silently testing nothing.
    """
    spec = plan.spec
    target_file = spec.target.split(":")[0]
    target_fn = spec.target.split(":")[-1] if ":" in spec.target else "LLVMFuzzerTestOneInput"
    stem = _stem(plan)

    content = f'''/* GENERATED BY KAVACHX — DO NOT EDIT
 *
 * plan_id : {plan.plan_id[:16]}
 * target  : {spec.target}
 * oracle  : {spec.oracle.kind}
 * property: {spec.expected_security_property[:100]}
 */
#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

/* Declared, not included: KavachX does not assume a header path it has not confirmed.
 *
 * The signature (const char *, size_t) is an ASSUMPTION. If the real target takes something
 * else, this fails at compile or link time — which is the honest outcome, and is reported as an
 * engine problem rather than as a test that passed. It is never reported as a clean result. */
extern void {target_fn}(const char *input, size_t length);

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {{
    if (size == 0 || size > 65536) {{
        return 0;
    }}
    char *buffer = (char *) malloc(size + 1);
    if (buffer == NULL) {{
        return 0;
    }}
    memcpy(buffer, data, size);
    buffer[size] = '\\0';
    {target_fn}(buffer, size);
    free(buffer);
    return 0;
}}
'''
    path = f"{HARNESS_DIR}/{stem}.c"
    iterations = spec.fuzz.max_iterations if spec.fuzz else 2000
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        # Build and run are separate steps; the caller runs the build first and reports a compile
        # failure as an engine problem rather than as a clean test.
        command=[
            "clang",
            "-g",
            "-O1",
            "-fsanitize=fuzzer,address,undefined",
            "-fno-omit-frame-pointer",
            path,
            target_file,
            "-o",
            f"{HARNESS_DIR}/{stem}.bin",
        ],
        artifacts=[],
        markers={},
        notes=[
            "clang with -fsanitize=fuzzer,address,undefined.",
            f"run: {HARNESS_DIR}/{stem}.bin -runs={iterations} "
            f"-artifact_prefix={HARNESS_DIR}/out/",
        ],
    )


# ---------------------------------------------------------------------------
# JavaScript / Go
# ---------------------------------------------------------------------------
def _js_property(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    spec = plan.spec
    entry = getattr(descriptor, "entry_file", "") or spec.target.split(":")[0]
    stem = _stem(plan)
    content = f'''// GENERATED BY KAVACHX — DO NOT EDIT
// plan_id : {plan.plan_id[:16]}
// target  : {spec.target}
// property: {spec.expected_security_property[:120]}
const fc = require('fast-check');
const target = require({_js_lit("./" + entry)});

const KX_MARKER = {_js_lit(POV_MARKER)};
const KX_CANARY = {_js_lit(CANARY_CONTENT)};
const TEMPLATE = {_js_lit(dict(spec.request_template or {}))};
const FIELD = {_js_lit(spec.payload_field or "value")};

fc.assert(
  fc.property(fc.string({{maxLength: 512}}), (value) => {{
    const request = Object.assign({{}}, TEMPLATE);
    request[FIELD] = value;
    let combined = '';
    try {{
      const fn = target.entrypoint || target.handle || target.main || target;
      combined = JSON.stringify(fn(request) ?? '');
    }} catch (err) {{
      combined = String(err && err.stack ? err.stack : err);
    }}
    // The property holds when neither marker appears.
    return !combined.includes(KX_MARKER) && !combined.includes(KX_CANARY);
  }}),
  {{numRuns: {min(spec.fuzz.max_iterations if spec.fuzz else 200, 5000)}}}
);
console.log(JSON.stringify({{ok: true}}));
'''
    path = f"{HARNESS_DIR}/{stem}.js"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["node", path],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
        notes=["fast-check property test with shrinking."],
    )


def _js_unit(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    spec = plan.spec
    entry = getattr(descriptor, "entry_file", "") or spec.target.split(":")[0]
    stem = _stem(plan)
    requests = _request_payloads(spec) or [{}]
    content = f'''// GENERATED BY KAVACHX — DO NOT EDIT
// plan_id : {plan.plan_id[:16]}
// property: {spec.expected_security_property[:120]}
const target = require({_js_lit("./" + entry)});

const KX_MARKER = {_js_lit(POV_MARKER)};
const KX_CANARY = {_js_lit(CANARY_CONTENT)};
const REQUESTS = {_js_lit(requests)};

let violations = [];
for (const request of REQUESTS) {{
  let combined = '';
  try {{
    const fn = target.entrypoint || target.handle || target.main || target;
    combined = JSON.stringify(fn(request) ?? '');
  }} catch (err) {{
    combined = String(err && err.stack ? err.stack : err);
  }}
  if (combined.includes(KX_MARKER) || combined.includes(KX_CANARY)) {{
    violations.push({{request, evidence: combined.slice(0, 400)}});
  }}
}}
console.log(JSON.stringify({{violations}}));
process.exit(violations.length ? 1 : 0);
'''
    path = f"{HARNESS_DIR}/{stem}.js"
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["node", path],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
    )


def _go_fuzz(plan: TestPlan, workspace: Path, descriptor: Any) -> GeneratedHarness:
    spec = plan.spec
    stem = _stem(plan)
    target_fn = spec.target.split(":")[-1] if ":" in spec.target else "Handle"
    content = f'''// GENERATED BY KAVACHX — DO NOT EDIT
// plan_id : {plan.plan_id[:16]}
// property: {spec.expected_security_property[:120]}
package main

import (
    "strings"
    "testing"
)

const kxMarker = {_js_lit(POV_MARKER)}
const kxCanary = {_js_lit(CANARY_CONTENT)}

func FuzzKavachX(f *testing.F) {{
    for _, seed := range []string{{{", ".join(_js_lit(s) for s in (spec.fuzz.seeds if spec.fuzz else [])[:16]) or '""'}}} {{
        f.Add(seed)
    }}
    f.Fuzz(func(t *testing.T, input string) {{
        out := captureOutput(func() {{ {target_fn}(input) }})
        if strings.Contains(out, kxMarker) || strings.Contains(out, kxCanary) {{
            t.Fatalf("SECURITY PROPERTY VIOLATED: %s", out[:min(len(out), 400)])
        }}
    }})
}}
'''
    path = f"{HARNESS_DIR}/{stem}_test.go"
    iterations = spec.fuzz.max_iterations if spec.fuzz else 1000
    return GeneratedHarness(
        ok=True,
        path=path,
        content=content,
        command=["go", "test", "-run=XXX", "-fuzz=FuzzKavachX", f"-fuzztime={iterations}x", "./..."],
        markers={"pov_marker": POV_MARKER, "canary": CANARY_CONTENT},
        notes=[
            "Requires a captureOutput helper in the target package; a compile failure here is "
            "reported as an engine problem, not as a passing test."
        ],
    )


# ---------------------------------------------------------------------------
def attach(plan: TestPlan, harness: GeneratedHarness) -> TestPlan:
    """Fold a generated harness back onto its plan."""
    if not harness.ok:
        plan.status = TestPlanStatus.UNSUPPORTED
        plan.notes.append(harness.error)
        return plan
    plan.status = TestPlanStatus.GENERATED
    plan.harness_path = harness.path
    plan.harness_sha256 = harness.sha256
    plan.command = harness.command
    plan.markers = harness.markers
    plan.notes.extend(harness.notes)
    return plan
