"""TestSpec — a structured testing *intention*, never executable code.

This is the boundary that keeps the model out of the execution path. The spec's requirement is
blunt: the LLM must not be able to run arbitrary generated commands. So the pipeline is

    LLM → TestSpec → Pydantic validation → harness generator → sandbox → oracle

and a model can only influence execution by filling in fields of :class:`TestSpec`. It cannot
supply code, a command, a path, an interpreter or a flag. Every one of those is either a
constrained enum, a workspace-relative path validated against the index, or generated by
:mod:`app.testing.harness` from a KavachX-authored template.

The three validators at the bottom of :class:`TestSpec` are the enforcement, not documentation:
payloads are size-capped, the target must be a real indexed symbol handle shape, and anything that
looks like shell metacharacters in a field destined for an argv is rejected outright rather than
escaped. Escaping is a judgement call; refusing is not.

What the model genuinely decides — and what it is good at — is *what to target, what inputs
matter, which mutations are valuable, and what property to assert*. That is the whole point of
having it in the loop.
"""

from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator


class StrictModel(BaseModel):
    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)


#: Testing strategies. Each maps to a generator in app.testing.harness; a strategy with no
#: generator for the detected language is reported as unavailable rather than silently skipped.
Strategy = Literal["unit", "property", "fuzz", "mutation", "regression", "differential"]

#: Deterministic signals an oracle may assert on. Every one is observable from an ExecResult or a
#: parsed observation file — there is no oracle here that requires a judgement call.
OracleKind = Literal[
    "exit_code_nonzero",
    "exit_code_equals",
    "crash_signal",
    "sanitizer_report",
    "exception_raised",
    "assertion_failure",
    "marker_in_stdout",
    "canary_content_in_stdout",
    "contract_violation",
    "output_differs_from_baseline",
    "timeout",
    "resource_exhaustion",
    "no_crash",
]

#: Where the harness gets its input from.
InputSource = Literal[
    "cli_argument",
    "cli_stdin",
    "http_request",
    "function_argument",
    "file_content",
    "environment_variable",
    "corpus_file",
]

#: Shell metacharacters and control constructs. A field that will end up inside an argv element
#: must not contain these: the sandbox never spawns a shell for KavachX, so their presence means
#: either a confused proposal or an attempt to reach one.
_ARGV_FORBIDDEN = re.compile(r"[\n\r\x00]")
#: Symbol handle shape: `path/to/file.ext:qualname` or `path/to/file.ext`.
_HANDLE = re.compile(r"^[\w\-./]+(\.[A-Za-z0-9]+)?(:[\w.<>]+)?$")

MAX_PAYLOAD_CHARS = 8_000
MAX_PAYLOADS = 64


class OracleSpec(StrictModel):
    """What outcome proves the security property was violated."""

    kind: OracleKind
    #: For ``exit_code_equals``.
    expected_exit_code: int | None = None
    #: For marker/canary oracles. KavachX supplies the actual marker value; the model may not,
    #: because a model-chosen marker could collide with the target's own output and manufacture a
    #: false positive.
    marker_role: Literal["pov_marker", "canary", "none"] = "none"
    #: For ``contract_violation``: the SAMHITA clause id expected to become false.
    clause_id: str = Field(default="", max_length=40)
    #: For ``exception_raised``: the exception type name expected in stderr.
    exception_type: str = Field(default="", max_length=80)
    description: str = Field(default="", max_length=400)

    @model_validator(mode="after")
    def _coherent(self) -> OracleSpec:
        if self.kind == "exit_code_equals" and self.expected_exit_code is None:
            raise ValueError("exit_code_equals requires expected_exit_code")
        if self.kind == "marker_in_stdout" and self.marker_role != "pov_marker":
            raise ValueError("marker_in_stdout requires marker_role='pov_marker'")
        if self.kind == "canary_content_in_stdout" and self.marker_role != "canary":
            raise ValueError("canary_content_in_stdout requires marker_role='canary'")
        return self


class FuzzSpec(StrictModel):
    """Fuzzing parameters. The engine is chosen by KavachX, not by the model.

    The model proposes *what to vary and why*; which fuzzer runs is a function of the detected
    language and the toolchain that is actually installed, and letting a model pick it would only
    produce specs naming engines that are not present.
    """

    #: Seed inputs to mutate. Bounded and validated like every other payload field.
    seeds: list[str] = Field(default_factory=list, max_length=MAX_PAYLOADS)
    #: Mutation families to prioritise. Advisory: the deterministic mutator owns the operators.
    mutations: list[
        Literal[
            "boundary_values",
            "negative_numbers",
            "large_values",
            "empty_and_null",
            "type_confusion",
            "encoding_variants",
            "separator_injection",
            "traversal_sequences",
            "length_escalation",
            "unicode_edge_cases",
            "format_specifiers",
            "structural_nesting",
        ]
    ] = Field(default_factory=list, max_length=12)
    #: Uncovered branches worth steering toward, as ``file:line``. Comes from coverage feedback.
    target_branches: list[str] = Field(default_factory=list, max_length=40)
    max_iterations: int = Field(default=100, ge=1, le=100_000)
    #: Stop as soon as the oracle fires. Almost always right: one reproduction is what validation
    #: needs, and continuing burns sandbox budget for nothing.
    stop_on_first_signal: bool = True


class TestSpec(StrictModel):
    """One executable test, described structurally."""

    #: Symbol handle or file path the test targets. Verified against the index before use.
    target: str = Field(min_length=1, max_length=400)
    #: The interface the harness drives. Verified against the confirmed descriptor.
    entrypoint: str = Field(default="", max_length=400)
    input_source: InputSource
    strategy: Strategy
    oracle: OracleSpec
    #: The security property the test is trying to violate, in one line. Prose, for the report.
    expected_security_property: str = Field(min_length=8, max_length=500)
    timeout_ms: int = Field(default=30_000, ge=100, le=600_000)

    #: Concrete inputs for unit/regression/mutation strategies.
    payloads: list[str] = Field(default_factory=list, max_length=MAX_PAYLOADS)
    #: For ``property``: the invariant, as a single boolean expression over the harness namespace.
    #: Compiled by the same restricted-AST whitelist SAMHITA uses, so it cannot execute anything.
    property_expression: str = Field(default="", max_length=400)
    fuzz: FuzzSpec | None = None

    #: Structured request fields for a CLI/HTTP target, e.g. {"op": "export", "name": "..."}.
    request_template: dict[str, Any] = Field(default_factory=dict)
    #: Which request field carries the payload.
    payload_field: str = Field(default="", max_length=120)

    cwe: str = Field(default="", max_length=32)
    rationale: str = Field(default="", max_length=1200)
    #: How many independent reproductions the validator should require.
    reproductions_required: int = Field(default=2, ge=1, le=10)

    # -- validation --------------------------------------------------------
    @field_validator("target", "entrypoint")
    @classmethod
    def _handle_shape(cls, v: str) -> str:
        if v and not _HANDLE.match(v):
            raise ValueError(
                f"{v!r} is not a symbol handle or path (expected 'path/file.py' or "
                "'path/file.py:qualname')"
            )
        if ".." in v:
            # A traversal sequence in a *target* is not a test payload, it is an attempt to point
            # the harness outside the workspace.
            raise ValueError("target/entrypoint may not contain '..'")
        return v

    @field_validator("payloads")
    @classmethod
    def _payload_limits(cls, v: list[str]) -> list[str]:
        for payload in v:
            if len(payload) > MAX_PAYLOAD_CHARS:
                raise ValueError(
                    f"payload exceeds {MAX_PAYLOAD_CHARS} characters; a test input this large is "
                    "a resource problem, not a test"
                )
            if _ARGV_FORBIDDEN.search(payload):
                # Newlines and NULs in an argv element break the harness's own framing. A payload
                # that genuinely needs them goes through a corpus file, which is a separate
                # input_source with its own handling.
                raise ValueError(
                    "payload contains a newline or NUL; use input_source='corpus_file' for "
                    "multi-line input"
                )
        return v

    @field_validator("property_expression")
    @classmethod
    def _expression_only(cls, v: str) -> str:
        if v and ("\n" in v or ";" in v or "import" in v):
            raise ValueError("property_expression must be a single expression with no statements")
        return v

    @model_validator(mode="after")
    def _strategy_coherent(self) -> TestSpec:
        if self.strategy == "fuzz" and self.fuzz is None:
            raise ValueError("strategy='fuzz' requires a fuzz block")
        if self.strategy == "property" and not self.property_expression:
            raise ValueError("strategy='property' requires property_expression")
        if (
            self.strategy in ("unit", "regression", "mutation")
            and not self.payloads
            and not self.request_template
        ):
            # Either is sufficient. A regression test built from a reproduction record often has
            # no separable "payload": the thing that reproduced was a whole request, and the test
            # is a replay of it. Demanding a payload there rejected a valid regression spec for a
            # genuinely reproduced finding, which cost the run its regression guard.
            raise ValueError(
                f"strategy={self.strategy!r} requires at least one payload or a request_template "
                "to replay"
            )
        if self.strategy == "differential" and self.oracle.kind != "output_differs_from_baseline":
            raise ValueError(
                "strategy='differential' requires oracle.kind='output_differs_from_baseline'"
            )
        if self.payloads and self.request_template and not self.payload_field:
            raise ValueError(
                "payloads with a request_template require payload_field naming which field "
                "carries the payload"
            )
        return self

    def as_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json")


class TestSpecProposal(StrictModel):
    """What the model returns. A list of intentions, nothing more."""

    specs: list[TestSpec] = Field(default_factory=list, max_length=12)
    #: Why these, in this order. Prose for the report; carries no authority.
    strategy_note: str = Field(default="", max_length=1200)


class FuzzStrategyProposal(StrictModel):
    """A revised fuzzing strategy, proposed from coverage feedback."""

    mutations: list[str] = Field(default_factory=list, max_length=12)
    #: Concrete inputs the model thinks will reach an uncovered branch. Executed, then judged by
    #: whether coverage actually moved — the model's belief is never the verdict.
    candidate_inputs: list[str] = Field(default_factory=list, max_length=64)
    target_branches: list[str] = Field(default_factory=list, max_length=40)
    rationale: str = Field(default="", max_length=1000)

    @field_validator("candidate_inputs")
    @classmethod
    def _bounded(cls, v: list[str]) -> list[str]:
        for item in v:
            if len(item) > MAX_PAYLOAD_CHARS:
                raise ValueError(f"candidate input exceeds {MAX_PAYLOAD_CHARS} characters")
        return v


# ---------------------------------------------------------------------------
class TestPlanStatus:
    PLANNED = "PLANNED"
    GENERATED = "GENERATED"
    #: A strategy with no available engine/generator for this target.
    UNSUPPORTED = "UNSUPPORTED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class TestPlan(BaseModel):
    """A validated spec plus everything KavachX derived around it.

    Deliberately not a ``StrictModel``: this is KavachX's own record, assembled after validation,
    and it carries fields a model is never allowed to set (the resolved engine, the generated
    harness path, the marker values).
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    spec: TestSpec
    #: Stable id: sha256 over the canonical spec plus the target's index id.
    plan_id: str = ""
    candidate_ref: str = ""
    finding_handle: str = ""
    status: str = TestPlanStatus.PLANNED
    #: Chosen by KavachX from the detected language and installed toolchain.
    engine: str = ""
    engine_available: bool = False
    engine_reason: str = ""
    language: str = ""
    #: Workspace-relative path of the generated harness, once generated.
    harness_path: str = ""
    harness_sha256: str = ""
    #: The argv the sandbox will run. Built by KavachX; never model-supplied.
    command: list[str] = Field(default_factory=list)
    #: Marker values injected by KavachX for marker/canary oracles.
    markers: dict[str, str] = Field(default_factory=dict)
    #: Why this plan exists, in evidence terms.
    provenance: dict[str, Any] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "candidate_ref": self.candidate_ref,
            "finding_handle": self.finding_handle,
            "status": self.status,
            "engine": self.engine,
            "engine_available": self.engine_available,
            "engine_reason": self.engine_reason,
            "language": self.language,
            "harness_path": self.harness_path,
            "harness_sha256": self.harness_sha256,
            "command": self.command,
            "spec": self.spec.as_dict(),
            "provenance": self.provenance,
            "notes": self.notes,
        }


def plan_id_for(spec: TestSpec, *, index_id: str) -> str:
    """Reproducible plan identity.

    Includes the index id so the same spec against a different commit is a different plan — a
    harness is only meaningful against the tree it was generated for.
    """
    from app.core.hashing import sha256_json

    return sha256_json({"spec": spec.as_dict(), "index_id": index_id})
